/**
 * Curated emoji catalog organized into the typical picker categories.
 *
 * This is intentionally NOT the full Unicode set — shipping ~1800
 * glyphs inflates the bundle and makes the grid overwhelming. The
 * selection covers the emojis users realistically reach for in notes
 * (feelings, tasks, objects, tech, symbols, common food/nature) while
 * keeping the list scrollable by hand if search fails.
 *
 * Each entry carries `keywords` for substring search. They're plain
 * ASCII so search works regardless of the OS locale.
 */

export interface EmojiEntry {
  char: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  labelFr: string;
  labelEn: string;
  emojis: EmojiEntry[];
}

// Keep category ids stable — they're persisted for "most recent" tracking.
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    labelFr: 'Smileys & émotions',
    labelEn: 'Smileys & emotions',
    emojis: [
      { char: '😀', keywords: ['grinning', 'happy', 'smile'] },
      { char: '😃', keywords: ['smiley', 'happy'] },
      { char: '😄', keywords: ['smile', 'happy', 'joy'] },
      { char: '😁', keywords: ['beaming', 'grin'] },
      { char: '😊', keywords: ['blush', 'smile', 'happy'] },
      { char: '😇', keywords: ['innocent', 'halo', 'angel'] },
      { char: '🙂', keywords: ['slight', 'smile'] },
      { char: '😉', keywords: ['wink'] },
      { char: '😌', keywords: ['relieved', 'peaceful'] },
      { char: '😍', keywords: ['heart', 'eyes', 'love'] },
      { char: '🥰', keywords: ['hearts', 'love', 'crush'] },
      { char: '😘', keywords: ['kiss', 'love'] },
      { char: '😎', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', keywords: ['nerd', 'glasses', 'geek'] },
      { char: '🧐', keywords: ['monocle', 'inspect'] },
      { char: '🤔', keywords: ['thinking', 'think', 'hmm'] },
      { char: '😐', keywords: ['neutral'] },
      { char: '😶', keywords: ['speechless', 'silent'] },
      { char: '😏', keywords: ['smirk'] },
      { char: '😒', keywords: ['unamused', 'meh'] },
      { char: '🙄', keywords: ['eyeroll', 'eye', 'roll'] },
      { char: '😬', keywords: ['grimace', 'awkward'] },
      { char: '🤐', keywords: ['zipper', 'mouth', 'quiet'] },
      { char: '😴', keywords: ['sleep', 'tired'] },
      { char: '🤯', keywords: ['mind', 'blown', 'explode'] },
      { char: '🥳', keywords: ['party', 'celebrate'] },
      { char: '😢', keywords: ['cry', 'sad'] },
      { char: '😭', keywords: ['sob', 'crying', 'sad'] },
      { char: '😤', keywords: ['triumph', 'huff'] },
      { char: '😡', keywords: ['angry', 'mad', 'rage'] },
      { char: '🤬', keywords: ['swear', 'cursing'] },
      { char: '🤒', keywords: ['sick', 'thermometer'] },
      { char: '🥴', keywords: ['woozy', 'drunk'] },
      { char: '🥱', keywords: ['yawn', 'tired', 'boring'] },
      { char: '💀', keywords: ['skull', 'dead'] },
      { char: '👻', keywords: ['ghost', 'halloween'] },
      { char: '👽', keywords: ['alien'] },
      { char: '🤖', keywords: ['robot', 'bot', 'ai'] },
    ],
  },
  {
    id: 'people',
    labelFr: 'Personnes & corps',
    labelEn: 'People & body',
    emojis: [
      { char: '👋', keywords: ['wave', 'hello', 'bye'] },
      { char: '🤚', keywords: ['stop', 'hand'] },
      { char: '✋', keywords: ['stop', 'hand'] },
      { char: '👌', keywords: ['ok'] },
      { char: '🤌', keywords: ['pinched', 'italian'] },
      { char: '🤏', keywords: ['pinch', 'small'] },
      { char: '✌️', keywords: ['peace', 'victory'] },
      { char: '🤞', keywords: ['fingers', 'crossed'] },
      { char: '🤟', keywords: ['love', 'rock'] },
      { char: '🤘', keywords: ['rock', 'horns'] },
      { char: '🤙', keywords: ['call', 'shaka'] },
      { char: '👈', keywords: ['left', 'point'] },
      { char: '👉', keywords: ['right', 'point'] },
      { char: '👆', keywords: ['up', 'point'] },
      { char: '👇', keywords: ['down', 'point'] },
      { char: '☝️', keywords: ['up', 'index'] },
      { char: '👍', keywords: ['thumbs', 'up', 'yes', 'like'] },
      { char: '👎', keywords: ['thumbs', 'down', 'no', 'dislike'] },
      { char: '✊', keywords: ['fist'] },
      { char: '👊', keywords: ['punch', 'bump'] },
      { char: '🙌', keywords: ['hands', 'up', 'celebrate'] },
      { char: '👏', keywords: ['clap', 'applause'] },
      { char: '🤝', keywords: ['handshake', 'deal'] },
      { char: '🙏', keywords: ['pray', 'thanks'] },
      { char: '💪', keywords: ['muscle', 'strong', 'flex'] },
      { char: '🧠', keywords: ['brain', 'smart'] },
      { char: '👀', keywords: ['eyes', 'look'] },
      { char: '👂', keywords: ['ear', 'listen'] },
      { char: '👶', keywords: ['baby'] },
      { char: '🧑', keywords: ['person', 'adult'] },
      { char: '👨', keywords: ['man'] },
      { char: '👩', keywords: ['woman'] },
      { char: '🧓', keywords: ['elder'] },
      { char: '👨‍💻', keywords: ['developer', 'coder', 'tech'] },
      { char: '👩‍💻', keywords: ['developer', 'coder', 'tech'] },
      { char: '🧑‍🎓', keywords: ['student'] },
      { char: '🧑‍🏫', keywords: ['teacher'] },
      { char: '🧑‍🎨', keywords: ['artist'] },
      { char: '🧑‍🔬', keywords: ['scientist'] },
    ],
  },
  {
    id: 'nature',
    labelFr: 'Nature & animaux',
    labelEn: 'Nature & animals',
    emojis: [
      { char: '🐶', keywords: ['dog', 'puppy'] },
      { char: '🐱', keywords: ['cat', 'kitten'] },
      { char: '🐭', keywords: ['mouse'] },
      { char: '🐹', keywords: ['hamster'] },
      { char: '🐰', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', keywords: ['fox'] },
      { char: '🐻', keywords: ['bear'] },
      { char: '🐼', keywords: ['panda'] },
      { char: '🐨', keywords: ['koala'] },
      { char: '🐯', keywords: ['tiger'] },
      { char: '🦁', keywords: ['lion'] },
      { char: '🐮', keywords: ['cow'] },
      { char: '🐷', keywords: ['pig'] },
      { char: '🐸', keywords: ['frog'] },
      { char: '🐵', keywords: ['monkey'] },
      { char: '🦉', keywords: ['owl'] },
      { char: '🦅', keywords: ['eagle'] },
      { char: '🐺', keywords: ['wolf'] },
      { char: '🐴', keywords: ['horse'] },
      { char: '🦄', keywords: ['unicorn'] },
      { char: '🐝', keywords: ['bee'] },
      { char: '🦋', keywords: ['butterfly'] },
      { char: '🐌', keywords: ['snail', 'slow'] },
      { char: '🐢', keywords: ['turtle'] },
      { char: '🐍', keywords: ['snake'] },
      { char: '🐙', keywords: ['octopus'] },
      { char: '🦑', keywords: ['squid'] },
      { char: '🦈', keywords: ['shark'] },
      { char: '🐳', keywords: ['whale'] },
      { char: '🐬', keywords: ['dolphin'] },
      { char: '🐟', keywords: ['fish'] },
      { char: '🌸', keywords: ['flower', 'cherry', 'blossom'] },
      { char: '🌺', keywords: ['flower', 'hibiscus'] },
      { char: '🌻', keywords: ['sunflower'] },
      { char: '🌹', keywords: ['rose'] },
      { char: '🌷', keywords: ['tulip'] },
      { char: '🌳', keywords: ['tree'] },
      { char: '🌲', keywords: ['pine', 'evergreen', 'tree'] },
      { char: '🌵', keywords: ['cactus'] },
      { char: '🍀', keywords: ['clover', 'luck'] },
      { char: '🌱', keywords: ['seedling', 'plant', 'growth'] },
      { char: '🌍', keywords: ['earth', 'globe', 'world'] },
      { char: '🌙', keywords: ['moon', 'night'] },
      { char: '⭐', keywords: ['star'] },
      { char: '🌟', keywords: ['star', 'glow'] },
      { char: '⚡', keywords: ['lightning', 'zap', 'fast'] },
      { char: '🔥', keywords: ['fire', 'hot', 'flame'] },
      { char: '💧', keywords: ['water', 'drop', 'droplet'] },
      { char: '🌊', keywords: ['wave', 'ocean'] },
      { char: '❄️', keywords: ['snow', 'cold', 'winter'] },
      { char: '☀️', keywords: ['sun', 'sunny'] },
      { char: '🌈', keywords: ['rainbow'] },
    ],
  },
  {
    id: 'food',
    labelFr: 'Nourriture',
    labelEn: 'Food',
    emojis: [
      { char: '🍎', keywords: ['apple'] },
      { char: '🍊', keywords: ['orange'] },
      { char: '🍋', keywords: ['lemon'] },
      { char: '🍌', keywords: ['banana'] },
      { char: '🍉', keywords: ['watermelon'] },
      { char: '🍇', keywords: ['grapes'] },
      { char: '🍓', keywords: ['strawberry'] },
      { char: '🍒', keywords: ['cherries'] },
      { char: '🍑', keywords: ['peach'] },
      { char: '🥭', keywords: ['mango'] },
      { char: '🍍', keywords: ['pineapple'] },
      { char: '🥥', keywords: ['coconut'] },
      { char: '🥑', keywords: ['avocado'] },
      { char: '🍅', keywords: ['tomato'] },
      { char: '🥕', keywords: ['carrot'] },
      { char: '🌽', keywords: ['corn'] },
      { char: '🥔', keywords: ['potato'] },
      { char: '🍞', keywords: ['bread'] },
      { char: '🥐', keywords: ['croissant'] },
      { char: '🧀', keywords: ['cheese'] },
      { char: '🍕', keywords: ['pizza'] },
      { char: '🍔', keywords: ['burger'] },
      { char: '🌮', keywords: ['taco'] },
      { char: '🍜', keywords: ['ramen', 'noodles'] },
      { char: '🍣', keywords: ['sushi'] },
      { char: '🍦', keywords: ['ice', 'cream'] },
      { char: '🍪', keywords: ['cookie'] },
      { char: '🍫', keywords: ['chocolate'] },
      { char: '🍰', keywords: ['cake'] },
      { char: '🧁', keywords: ['cupcake'] },
      { char: '🍩', keywords: ['donut'] },
      { char: '☕', keywords: ['coffee', 'tea'] },
      { char: '🍵', keywords: ['tea', 'matcha'] },
      { char: '🍷', keywords: ['wine'] },
      { char: '🍺', keywords: ['beer'] },
      { char: '🥤', keywords: ['drink', 'cup', 'soda'] },
    ],
  },
  {
    id: 'activities',
    labelFr: 'Activités & loisirs',
    labelEn: 'Activities & hobbies',
    emojis: [
      { char: '⚽', keywords: ['soccer', 'football', 'ball'] },
      { char: '🏀', keywords: ['basketball'] },
      { char: '🏈', keywords: ['football', 'american'] },
      { char: '🎾', keywords: ['tennis'] },
      { char: '🏐', keywords: ['volleyball'] },
      { char: '🏓', keywords: ['ping', 'pong'] },
      { char: '⛳', keywords: ['golf'] },
      { char: '🎣', keywords: ['fishing'] },
      { char: '🎿', keywords: ['ski'] },
      { char: '🏄', keywords: ['surf'] },
      { char: '🏊', keywords: ['swim'] },
      { char: '🚴', keywords: ['bike', 'cycling'] },
      { char: '🧘', keywords: ['yoga', 'meditate'] },
      { char: '🎨', keywords: ['art', 'paint', 'palette'] },
      { char: '🎭', keywords: ['theatre', 'theater'] },
      { char: '🎤', keywords: ['microphone', 'sing', 'karaoke'] },
      { char: '🎧', keywords: ['headphones', 'music'] },
      { char: '🎵', keywords: ['music', 'note'] },
      { char: '🎸', keywords: ['guitar'] },
      { char: '🎹', keywords: ['piano', 'keyboard'] },
      { char: '🎺', keywords: ['trumpet'] },
      { char: '🥁', keywords: ['drum'] },
      { char: '🎬', keywords: ['movie', 'film', 'clapper'] },
      { char: '🎮', keywords: ['game', 'controller', 'gaming'] },
      { char: '🎲', keywords: ['dice', 'random'] },
      { char: '♟️', keywords: ['chess', 'pawn'] },
      { char: '🧩', keywords: ['puzzle'] },
      { char: '🏆', keywords: ['trophy', 'award', 'win'] },
      { char: '🥇', keywords: ['gold', 'medal', 'first'] },
      { char: '🎯', keywords: ['target', 'bullseye', 'goal'] },
      { char: '🎉', keywords: ['party', 'celebrate'] },
      { char: '🎊', keywords: ['confetti', 'party'] },
      { char: '🎁', keywords: ['gift', 'present'] },
      { char: '🎂', keywords: ['birthday', 'cake'] },
    ],
  },
  {
    id: 'travel',
    labelFr: 'Voyage & lieux',
    labelEn: 'Travel & places',
    emojis: [
      { char: '🚗', keywords: ['car'] },
      { char: '🚕', keywords: ['taxi'] },
      { char: '🚙', keywords: ['suv'] },
      { char: '🚌', keywords: ['bus'] },
      { char: '🚎', keywords: ['trolley'] },
      { char: '🏎️', keywords: ['race', 'car'] },
      { char: '🚓', keywords: ['police'] },
      { char: '🚑', keywords: ['ambulance'] },
      { char: '🚒', keywords: ['fire', 'truck'] },
      { char: '🚚', keywords: ['truck'] },
      { char: '🚲', keywords: ['bike', 'bicycle'] },
      { char: '🛴', keywords: ['scooter'] },
      { char: '🚅', keywords: ['train', 'bullet'] },
      { char: '🚀', keywords: ['rocket', 'launch', 'ship'] },
      { char: '✈️', keywords: ['plane', 'airplane', 'flight'] },
      { char: '🛫', keywords: ['departure', 'takeoff'] },
      { char: '🛬', keywords: ['landing', 'arrival'] },
      { char: '⛵', keywords: ['sailboat', 'boat'] },
      { char: '🚢', keywords: ['ship', 'cruise'] },
      { char: '🏠', keywords: ['home', 'house'] },
      { char: '🏡', keywords: ['house', 'garden'] },
      { char: '🏢', keywords: ['office', 'building'] },
      { char: '🏫', keywords: ['school'] },
      { char: '🏥', keywords: ['hospital'] },
      { char: '🏛️', keywords: ['classical', 'museum', 'building'] },
      { char: '🗽', keywords: ['liberty', 'statue'] },
      { char: '🗼', keywords: ['tokyo', 'tower'] },
      { char: '🏰', keywords: ['castle'] },
      { char: '🏖️', keywords: ['beach'] },
      { char: '🏕️', keywords: ['camp', 'camping'] },
      { char: '🌆', keywords: ['city', 'sunset'] },
      { char: '🌃', keywords: ['night', 'city'] },
      { char: '🗺️', keywords: ['map', 'world'] },
      { char: '🧭', keywords: ['compass', 'direction'] },
    ],
  },
  {
    id: 'objects',
    labelFr: 'Objets',
    labelEn: 'Objects',
    emojis: [
      { char: '💡', keywords: ['idea', 'light', 'bulb'] },
      { char: '🔦', keywords: ['flashlight'] },
      { char: '📚', keywords: ['books', 'library'] },
      { char: '📖', keywords: ['book', 'open', 'read'] },
      { char: '📕', keywords: ['book', 'red'] },
      { char: '📗', keywords: ['book', 'green'] },
      { char: '📘', keywords: ['book', 'blue'] },
      { char: '📝', keywords: ['memo', 'note', 'writing'] },
      { char: '✏️', keywords: ['pencil', 'write'] },
      { char: '✒️', keywords: ['pen', 'nib', 'write'] },
      { char: '🖋️', keywords: ['pen', 'fountain'] },
      { char: '🖌️', keywords: ['brush', 'paint'] },
      { char: '🖍️', keywords: ['crayon'] },
      { char: '📐', keywords: ['ruler', 'triangle'] },
      { char: '📏', keywords: ['ruler', 'straight'] },
      { char: '📌', keywords: ['pin', 'pushpin'] },
      { char: '📎', keywords: ['paperclip'] },
      { char: '📁', keywords: ['folder', 'file'] },
      { char: '📂', keywords: ['folder', 'open'] },
      { char: '🗂️', keywords: ['dividers', 'files'] },
      { char: '📅', keywords: ['calendar', 'date'] },
      { char: '📆', keywords: ['calendar'] },
      { char: '📊', keywords: ['chart', 'bar', 'stats'] },
      { char: '📈', keywords: ['chart', 'up', 'growth'] },
      { char: '📉', keywords: ['chart', 'down'] },
      { char: '📋', keywords: ['clipboard'] },
      { char: '📇', keywords: ['card', 'index'] },
      { char: '🔍', keywords: ['search', 'magnify'] },
      { char: '🔎', keywords: ['search', 'magnify'] },
      { char: '🔐', keywords: ['lock', 'key'] },
      { char: '🔒', keywords: ['lock', 'locked', 'secure'] },
      { char: '🔑', keywords: ['key'] },
      { char: '🗝️', keywords: ['key', 'old'] },
      { char: '💻', keywords: ['laptop', 'computer'] },
      { char: '🖥️', keywords: ['desktop', 'computer'] },
      { char: '⌨️', keywords: ['keyboard'] },
      { char: '🖱️', keywords: ['mouse', 'computer'] },
      { char: '🖨️', keywords: ['printer'] },
      { char: '📱', keywords: ['phone', 'mobile'] },
      { char: '☎️', keywords: ['phone', 'telephone'] },
      { char: '📷', keywords: ['camera', 'photo'] },
      { char: '📹', keywords: ['video', 'camera'] },
      { char: '💾', keywords: ['floppy', 'save', 'disk'] },
      { char: '💿', keywords: ['cd', 'disc'] },
      { char: '🔧', keywords: ['wrench', 'tool'] },
      { char: '🔨', keywords: ['hammer'] },
      { char: '⚙️', keywords: ['gear', 'settings'] },
      { char: '🧰', keywords: ['toolbox'] },
      { char: '🧪', keywords: ['test', 'tube', 'lab'] },
      { char: '🔬', keywords: ['microscope', 'science'] },
      { char: '🔭', keywords: ['telescope'] },
      { char: '💰', keywords: ['money', 'bag'] },
      { char: '💵', keywords: ['dollar', 'cash'] },
      { char: '💳', keywords: ['card', 'credit'] },
      { char: '💎', keywords: ['gem', 'diamond'] },
      { char: '🎓', keywords: ['graduation', 'cap'] },
      { char: '💼', keywords: ['briefcase', 'business'] },
    ],
  },
  {
    id: 'symbols',
    labelFr: 'Symboles',
    labelEn: 'Symbols',
    emojis: [
      { char: '❤️', keywords: ['heart', 'love', 'red'] },
      { char: '🧡', keywords: ['heart', 'orange'] },
      { char: '💛', keywords: ['heart', 'yellow'] },
      { char: '💚', keywords: ['heart', 'green'] },
      { char: '💙', keywords: ['heart', 'blue'] },
      { char: '💜', keywords: ['heart', 'purple'] },
      { char: '🖤', keywords: ['heart', 'black'] },
      { char: '🤍', keywords: ['heart', 'white'] },
      { char: '💔', keywords: ['heart', 'broken'] },
      { char: '❣️', keywords: ['heart', 'exclamation'] },
      { char: '💕', keywords: ['hearts', 'love'] },
      { char: '💖', keywords: ['sparkling', 'heart'] },
      { char: '✨', keywords: ['sparkle', 'magic'] },
      { char: '⭐', keywords: ['star'] },
      { char: '🌟', keywords: ['star', 'glow'] },
      { char: '💥', keywords: ['boom', 'explosion'] },
      { char: '💢', keywords: ['anger'] },
      { char: '💭', keywords: ['thought', 'bubble'] },
      { char: '💬', keywords: ['speech', 'bubble', 'chat'] },
      { char: '🗯️', keywords: ['right', 'anger', 'bubble'] },
      { char: '✅', keywords: ['check', 'done', 'ok', 'yes'] },
      { char: '✔️', keywords: ['check', 'mark'] },
      { char: '☑️', keywords: ['ballot', 'box', 'check'] },
      { char: '❌', keywords: ['cross', 'no', 'wrong'] },
      { char: '❎', keywords: ['no'] },
      { char: '⚠️', keywords: ['warning', 'caution', 'alert'] },
      { char: '🚫', keywords: ['prohibited', 'no'] },
      { char: '❓', keywords: ['question'] },
      { char: '❗', keywords: ['exclamation'] },
      { char: '⁉️', keywords: ['question', 'exclamation'] },
      { char: '💯', keywords: ['100', 'hundred', 'score'] },
      { char: '🔥', keywords: ['fire', 'hot'] },
      { char: '⚡', keywords: ['lightning', 'zap'] },
      { char: '♻️', keywords: ['recycle'] },
      { char: '♾️', keywords: ['infinity'] },
      { char: '🔰', keywords: ['beginner'] },
      { char: '🆕', keywords: ['new'] },
      { char: '🆓', keywords: ['free'] },
      { char: '🔝', keywords: ['top'] },
      { char: '➕', keywords: ['plus', 'add'] },
      { char: '➖', keywords: ['minus'] },
      { char: '➡️', keywords: ['right', 'arrow'] },
      { char: '⬅️', keywords: ['left', 'arrow'] },
      { char: '⬆️', keywords: ['up', 'arrow'] },
      { char: '⬇️', keywords: ['down', 'arrow'] },
      { char: '🔄', keywords: ['refresh', 'reload'] },
    ],
  },
];

const allEmojis: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

/**
 * Case-insensitive substring search over keywords. Returns empty when
 * the query is shorter than 2 chars — we don't want single-letter
 * queries to throw hundreds of matches at the UI.
 */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  return allEmojis.filter((e) => e.keywords.some((k) => k.includes(q)));
}
