/**
 * Curated Lucide icon catalog for the note icon picker.
 *
 * We ship ~150 icons hand-picked for note-header usage rather than
 * exposing the full 1400+ Lucide set — the grid would be unusable
 * and the bundle would balloon. Tree-shaking on `react-icons/lu` keeps
 * only what's imported by name here, so the cost is bounded.
 *
 * Icons are stored by `id` (the react-icons export name minus the
 * `Lu` prefix). A note's `icon` field encodes this as `lucide:<id>`
 * for round-trip resolution in the renderer.
 */

import React from 'react';
import {
  LuBook,
  LuBookOpen,
  LuBookMarked,
  LuBookmark,
  LuLibrary,
  LuFileText,
  LuFile,
  LuFolder,
  LuFolderOpen,
  LuLayers,
  LuArchive,
  LuInbox,
  LuSticker,
  LuTag,
  LuTags,
  LuHash,
  LuLink,
  LuExternalLink,
  LuPencil,
  LuPencilLine,
  LuHighlighter,
  LuPalette,
  LuBrush,
  LuSearch,
  LuFilter,
  LuSliders,
  LuCheck,
  LuCheckCheck,
  LuListChecks,
  LuListTodo,
  LuList,
  LuListOrdered,
  LuCheckSquare,
  LuLayoutGrid,
  LuLayoutList,
  LuKanban,
  LuCalendar,
  LuCalendarDays,
  LuCalendarCheck,
  LuCalendarClock,
  LuClock,
  LuAlarmClock,
  LuTimer,
  LuHourglass,
  LuSun,
  LuMoon,
  LuStar,
  LuSparkles,
  LuZap,
  LuFlame,
  LuCloud,
  LuCloudRain,
  LuSnowflake,
  LuRainbow,
  LuHeart,
  LuHeartPulse,
  LuSmile,
  LuLaugh,
  LuFrown,
  LuBrain,
  LuLightbulb,
  LuTarget,
  LuFlag,
  LuTrophy,
  LuMedal,
  LuAward,
  LuCrown,
  LuGem,
  LuKey,
  LuLock,
  LuUnlock,
  LuShield,
  LuShieldCheck,
  LuEye,
  LuEyeOff,
  LuUser,
  LuUsers,
  LuUserCheck,
  LuUserCircle,
  LuContact,
  LuAtSign,
  LuMail,
  LuMessageCircle,
  LuMessageSquare,
  LuPhone,
  LuSend,
  LuBell,
  LuMegaphone,
  LuHome,
  LuBuilding,
  LuStore,
  LuHotel,
  LuSchool,
  LuChurch,
  LuMap,
  LuMapPin,
  LuCompass,
  LuGlobe,
  LuPlane,
  LuCar,
  LuBike,
  LuTrain,
  LuRocket,
  LuShip,
  LuPackage,
  LuPackageOpen,
  LuTruck,
  LuShoppingBag,
  LuShoppingCart,
  LuCreditCard,
  LuWallet,
  LuDollarSign,
  LuBanknote,
  LuReceipt,
  LuPiggyBank,
  LuTrendingUp,
  LuTrendingDown,
  LuBarChart,
  LuLineChart,
  LuPieChart,
  LuActivity,
  LuGauge,
  LuMonitor,
  LuLaptop,
  LuSmartphone,
  LuTablet,
  LuWatch,
  LuMouse,
  LuKeyboard,
  LuCpu,
  LuHardDrive,
  LuDatabase,
  LuServer,
  LuCode,
  LuTerminal,
  LuGitBranch,
  LuGithub,
  LuPlay,
  LuPause,
  LuVolume2,
  LuMusic,
  LuHeadphones,
  LuMic,
  LuVideo,
  LuCamera,
  LuImage,
  LuFilm,
  LuTv,
  LuGamepad2,
  LuPuzzle,
  LuDices,
  LuCoffee,
  LuUtensils,
  LuPizza,
  LuCake,
  LuWine,
  LuBeer,
  LuApple,
  LuDumbbell,
  LuBike as LuCycling,
  LuWaves,
  LuTreePine,
  LuFlower,
  LuLeaf,
  LuMountain,
  LuTent,
  LuUmbrella,
  LuBug,
  LuBird,
  LuFish,
  LuDog,
  LuCat,
  LuWrench,
  LuHammer,
  LuRuler,
  LuScissors,
  LuPipette,
  LuMagnet,
  LuMicroscope,
  LuAtom,
  LuFlaskConical,
  LuBeaker,
  LuDna,
  LuSettings,
  LuCog,
  LuPower,
  LuRefreshCw,
  LuRotateCw,
  LuSave,
  LuDownload,
  LuUpload,
  LuShare,
  LuCopy,
  LuTrash,
  LuTrash2,
  LuPlus,
  LuMinus,
  LuX,
  LuArrowRight,
  LuArrowLeft,
  LuArrowUp,
  LuArrowDown,
  LuChevronRight,
  LuMoreHorizontal,
} from 'react-icons/lu';
import type { IconType } from 'react-icons';

export interface IconEntry {
  id: string; // matches the lucide name without the Lu prefix
  keywords: string[];
  Component: IconType;
}

export interface IconCategory {
  id: string;
  labelFr: string;
  labelEn: string;
  icons: IconEntry[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'docs',
    labelFr: 'Documents & fichiers',
    labelEn: 'Documents & files',
    icons: [
      { id: 'Book', keywords: ['book', 'read'], Component: LuBook },
      { id: 'BookOpen', keywords: ['book', 'open', 'read'], Component: LuBookOpen },
      { id: 'BookMarked', keywords: ['book', 'bookmark'], Component: LuBookMarked },
      { id: 'Bookmark', keywords: ['bookmark', 'save'], Component: LuBookmark },
      { id: 'Library', keywords: ['library', 'books'], Component: LuLibrary },
      { id: 'FileText', keywords: ['file', 'document', 'text'], Component: LuFileText },
      { id: 'File', keywords: ['file', 'document'], Component: LuFile },
      { id: 'Folder', keywords: ['folder', 'directory'], Component: LuFolder },
      { id: 'FolderOpen', keywords: ['folder', 'open'], Component: LuFolderOpen },
      { id: 'Layers', keywords: ['layers', 'stack'], Component: LuLayers },
      { id: 'Archive', keywords: ['archive', 'box'], Component: LuArchive },
      { id: 'Inbox', keywords: ['inbox', 'mail'], Component: LuInbox },
      { id: 'Sticker', keywords: ['sticker', 'label'], Component: LuSticker },
      { id: 'Tag', keywords: ['tag', 'label'], Component: LuTag },
      { id: 'Tags', keywords: ['tags', 'labels'], Component: LuTags },
      { id: 'Hash', keywords: ['hash', 'tag', 'number'], Component: LuHash },
      { id: 'Link', keywords: ['link', 'url'], Component: LuLink },
      { id: 'ExternalLink', keywords: ['link', 'external', 'open'], Component: LuExternalLink },
    ],
  },
  {
    id: 'edit',
    labelFr: 'Édition',
    labelEn: 'Editing',
    icons: [
      { id: 'Pencil', keywords: ['pencil', 'write', 'edit'], Component: LuPencil },
      { id: 'PencilLine', keywords: ['pen', 'write'], Component: LuPencilLine },
      { id: 'Highlighter', keywords: ['highlighter', 'marker'], Component: LuHighlighter },
      { id: 'Palette', keywords: ['palette', 'colors'], Component: LuPalette },
      { id: 'Brush', keywords: ['brush', 'paint'], Component: LuBrush },
      { id: 'Search', keywords: ['search', 'find'], Component: LuSearch },
      { id: 'Filter', keywords: ['filter', 'sort'], Component: LuFilter },
      { id: 'Sliders', keywords: ['sliders', 'settings'], Component: LuSliders },
      { id: 'Check', keywords: ['check', 'done'], Component: LuCheck },
      { id: 'CheckCheck', keywords: ['check', 'done', 'double'], Component: LuCheckCheck },
      { id: 'ListChecks', keywords: ['list', 'checks', 'todo'], Component: LuListChecks },
      { id: 'ListTodo', keywords: ['todo', 'list'], Component: LuListTodo },
      { id: 'List', keywords: ['list', 'bullet'], Component: LuList },
      { id: 'ListOrdered', keywords: ['list', 'numbered'], Component: LuListOrdered },
      { id: 'CheckSquare', keywords: ['check', 'square', 'task'], Component: LuCheckSquare },
      { id: 'LayoutGrid', keywords: ['layout', 'grid'], Component: LuLayoutGrid },
      { id: 'LayoutList', keywords: ['layout', 'list'], Component: LuLayoutList },
      { id: 'Kanban', keywords: ['kanban', 'board'], Component: LuKanban },
    ],
  },
  {
    id: 'time',
    labelFr: 'Temps & calendrier',
    labelEn: 'Time & calendar',
    icons: [
      { id: 'Calendar', keywords: ['calendar', 'date'], Component: LuCalendar },
      { id: 'CalendarDays', keywords: ['calendar', 'week'], Component: LuCalendarDays },
      { id: 'CalendarCheck', keywords: ['calendar', 'done'], Component: LuCalendarCheck },
      { id: 'CalendarClock', keywords: ['calendar', 'time'], Component: LuCalendarClock },
      { id: 'Clock', keywords: ['clock', 'time'], Component: LuClock },
      { id: 'AlarmClock', keywords: ['alarm', 'clock'], Component: LuAlarmClock },
      { id: 'Timer', keywords: ['timer', 'stopwatch'], Component: LuTimer },
      { id: 'Hourglass', keywords: ['hourglass', 'wait'], Component: LuHourglass },
    ],
  },
  {
    id: 'nature',
    labelFr: 'Nature & météo',
    labelEn: 'Nature & weather',
    icons: [
      { id: 'Sun', keywords: ['sun', 'sunny'], Component: LuSun },
      { id: 'Moon', keywords: ['moon', 'night'], Component: LuMoon },
      { id: 'Star', keywords: ['star', 'favorite'], Component: LuStar },
      { id: 'Sparkles', keywords: ['sparkles', 'magic'], Component: LuSparkles },
      { id: 'Zap', keywords: ['zap', 'lightning', 'bolt'], Component: LuZap },
      { id: 'Flame', keywords: ['flame', 'fire', 'hot'], Component: LuFlame },
      { id: 'Cloud', keywords: ['cloud'], Component: LuCloud },
      { id: 'CloudRain', keywords: ['cloud', 'rain', 'weather'], Component: LuCloudRain },
      { id: 'Snowflake', keywords: ['snow', 'cold', 'winter'], Component: LuSnowflake },
      { id: 'Rainbow', keywords: ['rainbow', 'pride'], Component: LuRainbow },
      { id: 'TreePine', keywords: ['tree', 'pine', 'forest'], Component: LuTreePine },
      { id: 'Flower', keywords: ['flower', 'plant'], Component: LuFlower },
      { id: 'Leaf', keywords: ['leaf', 'plant', 'eco'], Component: LuLeaf },
      { id: 'Mountain', keywords: ['mountain', 'peak'], Component: LuMountain },
      { id: 'Waves', keywords: ['waves', 'ocean', 'water'], Component: LuWaves },
    ],
  },
  {
    id: 'people',
    labelFr: 'Personnes & émotions',
    labelEn: 'People & emotions',
    icons: [
      { id: 'Heart', keywords: ['heart', 'love'], Component: LuHeart },
      { id: 'HeartPulse', keywords: ['heart', 'pulse', 'health'], Component: LuHeartPulse },
      { id: 'Smile', keywords: ['smile', 'happy'], Component: LuSmile },
      { id: 'Laugh', keywords: ['laugh', 'happy'], Component: LuLaugh },
      { id: 'Frown', keywords: ['frown', 'sad'], Component: LuFrown },
      { id: 'Brain', keywords: ['brain', 'think', 'smart'], Component: LuBrain },
      { id: 'Lightbulb', keywords: ['idea', 'bulb', 'light'], Component: LuLightbulb },
      { id: 'Target', keywords: ['target', 'goal', 'bullseye'], Component: LuTarget },
      { id: 'Flag', keywords: ['flag', 'goal'], Component: LuFlag },
      { id: 'Trophy', keywords: ['trophy', 'win', 'award'], Component: LuTrophy },
      { id: 'Medal', keywords: ['medal', 'award'], Component: LuMedal },
      { id: 'Award', keywords: ['award', 'prize'], Component: LuAward },
      { id: 'Crown', keywords: ['crown', 'king', 'queen'], Component: LuCrown },
      { id: 'Gem', keywords: ['gem', 'diamond'], Component: LuGem },
      { id: 'User', keywords: ['user', 'person'], Component: LuUser },
      { id: 'Users', keywords: ['users', 'group'], Component: LuUsers },
      { id: 'UserCheck', keywords: ['user', 'verified'], Component: LuUserCheck },
      { id: 'UserCircle', keywords: ['user', 'profile'], Component: LuUserCircle },
      { id: 'Contact', keywords: ['contact', 'person'], Component: LuContact },
      { id: 'Eye', keywords: ['eye', 'visible'], Component: LuEye },
      { id: 'EyeOff', keywords: ['eye', 'hidden'], Component: LuEyeOff },
    ],
  },
  {
    id: 'security',
    labelFr: 'Sécurité & accès',
    labelEn: 'Security & access',
    icons: [
      { id: 'Key', keywords: ['key'], Component: LuKey },
      { id: 'Lock', keywords: ['lock', 'secure'], Component: LuLock },
      { id: 'Unlock', keywords: ['unlock', 'open'], Component: LuUnlock },
      { id: 'Shield', keywords: ['shield', 'protect'], Component: LuShield },
      { id: 'ShieldCheck', keywords: ['shield', 'secure', 'verified'], Component: LuShieldCheck },
    ],
  },
  {
    id: 'communication',
    labelFr: 'Communication',
    labelEn: 'Communication',
    icons: [
      { id: 'AtSign', keywords: ['at', 'email', 'mention'], Component: LuAtSign },
      { id: 'Mail', keywords: ['mail', 'email'], Component: LuMail },
      { id: 'MessageCircle', keywords: ['message', 'chat'], Component: LuMessageCircle },
      { id: 'MessageSquare', keywords: ['message', 'chat'], Component: LuMessageSquare },
      { id: 'Phone', keywords: ['phone', 'call'], Component: LuPhone },
      { id: 'Send', keywords: ['send'], Component: LuSend },
      { id: 'Bell', keywords: ['bell', 'notification'], Component: LuBell },
      { id: 'Megaphone', keywords: ['megaphone', 'announce'], Component: LuMegaphone },
    ],
  },
  {
    id: 'places',
    labelFr: 'Lieux & voyage',
    labelEn: 'Places & travel',
    icons: [
      { id: 'Home', keywords: ['home', 'house'], Component: LuHome },
      { id: 'Building', keywords: ['building', 'office'], Component: LuBuilding },
      { id: 'Store', keywords: ['store', 'shop'], Component: LuStore },
      { id: 'Hotel', keywords: ['hotel'], Component: LuHotel },
      { id: 'School', keywords: ['school', 'education'], Component: LuSchool },
      { id: 'Church', keywords: ['church'], Component: LuChurch },
      { id: 'Map', keywords: ['map'], Component: LuMap },
      { id: 'MapPin', keywords: ['pin', 'location'], Component: LuMapPin },
      { id: 'Compass', keywords: ['compass', 'direction'], Component: LuCompass },
      { id: 'Globe', keywords: ['globe', 'world', 'earth'], Component: LuGlobe },
      { id: 'Tent', keywords: ['tent', 'camping'], Component: LuTent },
      { id: 'Umbrella', keywords: ['umbrella', 'rain'], Component: LuUmbrella },
    ],
  },
  {
    id: 'transport',
    labelFr: 'Transport',
    labelEn: 'Transport',
    icons: [
      { id: 'Plane', keywords: ['plane', 'flight'], Component: LuPlane },
      { id: 'Car', keywords: ['car'], Component: LuCar },
      { id: 'Bike', keywords: ['bike', 'bicycle'], Component: LuBike },
      { id: 'Train', keywords: ['train'], Component: LuTrain },
      { id: 'Rocket', keywords: ['rocket', 'launch'], Component: LuRocket },
      { id: 'Ship', keywords: ['ship', 'boat'], Component: LuShip },
      { id: 'Truck', keywords: ['truck'], Component: LuTruck },
    ],
  },
  {
    id: 'commerce',
    labelFr: 'Commerce & finance',
    labelEn: 'Commerce & finance',
    icons: [
      { id: 'Package', keywords: ['package', 'box'], Component: LuPackage },
      { id: 'PackageOpen', keywords: ['package', 'open'], Component: LuPackageOpen },
      { id: 'ShoppingBag', keywords: ['shopping', 'bag'], Component: LuShoppingBag },
      { id: 'ShoppingCart', keywords: ['shopping', 'cart'], Component: LuShoppingCart },
      { id: 'CreditCard', keywords: ['card', 'credit'], Component: LuCreditCard },
      { id: 'Wallet', keywords: ['wallet', 'money'], Component: LuWallet },
      { id: 'DollarSign', keywords: ['dollar', 'money'], Component: LuDollarSign },
      { id: 'Banknote', keywords: ['money', 'cash'], Component: LuBanknote },
      { id: 'Receipt', keywords: ['receipt', 'bill'], Component: LuReceipt },
      { id: 'PiggyBank', keywords: ['savings', 'piggy'], Component: LuPiggyBank },
    ],
  },
  {
    id: 'data',
    labelFr: 'Données & analytics',
    labelEn: 'Data & analytics',
    icons: [
      { id: 'TrendingUp', keywords: ['trending', 'up', 'growth'], Component: LuTrendingUp },
      { id: 'TrendingDown', keywords: ['trending', 'down'], Component: LuTrendingDown },
      { id: 'BarChart', keywords: ['chart', 'bar', 'stats'], Component: LuBarChart },
      { id: 'LineChart', keywords: ['chart', 'line'], Component: LuLineChart },
      { id: 'PieChart', keywords: ['chart', 'pie'], Component: LuPieChart },
      { id: 'Activity', keywords: ['activity', 'pulse'], Component: LuActivity },
      { id: 'Gauge', keywords: ['gauge', 'speed'], Component: LuGauge },
      { id: 'Database', keywords: ['database', 'storage'], Component: LuDatabase },
      { id: 'Server', keywords: ['server'], Component: LuServer },
      { id: 'HardDrive', keywords: ['drive', 'storage'], Component: LuHardDrive },
    ],
  },
  {
    id: 'tech',
    labelFr: 'Technologie',
    labelEn: 'Technology',
    icons: [
      { id: 'Monitor', keywords: ['monitor', 'screen'], Component: LuMonitor },
      { id: 'Laptop', keywords: ['laptop'], Component: LuLaptop },
      { id: 'Smartphone', keywords: ['phone', 'mobile'], Component: LuSmartphone },
      { id: 'Tablet', keywords: ['tablet'], Component: LuTablet },
      { id: 'Watch', keywords: ['watch', 'smartwatch'], Component: LuWatch },
      { id: 'Mouse', keywords: ['mouse'], Component: LuMouse },
      { id: 'Keyboard', keywords: ['keyboard'], Component: LuKeyboard },
      { id: 'Cpu', keywords: ['cpu', 'chip'], Component: LuCpu },
      { id: 'Code', keywords: ['code', 'programming'], Component: LuCode },
      { id: 'Terminal', keywords: ['terminal', 'console'], Component: LuTerminal },
      { id: 'GitBranch', keywords: ['git', 'branch'], Component: LuGitBranch },
      { id: 'Github', keywords: ['github'], Component: LuGithub },
    ],
  },
  {
    id: 'media',
    labelFr: 'Médias & divertissement',
    labelEn: 'Media & entertainment',
    icons: [
      { id: 'Play', keywords: ['play'], Component: LuPlay },
      { id: 'Pause', keywords: ['pause'], Component: LuPause },
      { id: 'Volume2', keywords: ['volume', 'sound'], Component: LuVolume2 },
      { id: 'Music', keywords: ['music'], Component: LuMusic },
      { id: 'Headphones', keywords: ['headphones', 'audio'], Component: LuHeadphones },
      { id: 'Mic', keywords: ['mic', 'microphone'], Component: LuMic },
      { id: 'Video', keywords: ['video'], Component: LuVideo },
      { id: 'Camera', keywords: ['camera', 'photo'], Component: LuCamera },
      { id: 'Image', keywords: ['image', 'photo'], Component: LuImage },
      { id: 'Film', keywords: ['film', 'movie'], Component: LuFilm },
      { id: 'Tv', keywords: ['tv'], Component: LuTv },
      { id: 'Gamepad2', keywords: ['game', 'gaming'], Component: LuGamepad2 },
      { id: 'Puzzle', keywords: ['puzzle'], Component: LuPuzzle },
      { id: 'Dices', keywords: ['dice', 'random'], Component: LuDices },
    ],
  },
  {
    id: 'food',
    labelFr: 'Nourriture & boissons',
    labelEn: 'Food & drinks',
    icons: [
      { id: 'Coffee', keywords: ['coffee'], Component: LuCoffee },
      { id: 'Utensils', keywords: ['utensils', 'food'], Component: LuUtensils },
      { id: 'Pizza', keywords: ['pizza'], Component: LuPizza },
      { id: 'Cake', keywords: ['cake', 'birthday'], Component: LuCake },
      { id: 'Wine', keywords: ['wine'], Component: LuWine },
      { id: 'Beer', keywords: ['beer'], Component: LuBeer },
      { id: 'Apple', keywords: ['apple', 'fruit'], Component: LuApple },
    ],
  },
  {
    id: 'lifestyle',
    labelFr: 'Lifestyle',
    labelEn: 'Lifestyle',
    icons: [
      { id: 'Dumbbell', keywords: ['dumbbell', 'gym', 'workout'], Component: LuDumbbell },
      { id: 'Cycling', keywords: ['cycling', 'bike'], Component: LuCycling },
    ],
  },
  {
    id: 'animals',
    labelFr: 'Animaux',
    labelEn: 'Animals',
    icons: [
      { id: 'Bug', keywords: ['bug'], Component: LuBug },
      { id: 'Bird', keywords: ['bird'], Component: LuBird },
      { id: 'Fish', keywords: ['fish'], Component: LuFish },
      { id: 'Dog', keywords: ['dog'], Component: LuDog },
      { id: 'Cat', keywords: ['cat'], Component: LuCat },
    ],
  },
  {
    id: 'tools',
    labelFr: 'Outils & science',
    labelEn: 'Tools & science',
    icons: [
      { id: 'Wrench', keywords: ['wrench', 'tool'], Component: LuWrench },
      { id: 'Hammer', keywords: ['hammer'], Component: LuHammer },
      { id: 'Ruler', keywords: ['ruler', 'measure'], Component: LuRuler },
      { id: 'Scissors', keywords: ['scissors', 'cut'], Component: LuScissors },
      { id: 'Pipette', keywords: ['pipette'], Component: LuPipette },
      { id: 'Magnet', keywords: ['magnet'], Component: LuMagnet },
      { id: 'Microscope', keywords: ['microscope'], Component: LuMicroscope },
      { id: 'Atom', keywords: ['atom', 'science'], Component: LuAtom },
      { id: 'FlaskConical', keywords: ['flask', 'lab'], Component: LuFlaskConical },
      { id: 'Beaker', keywords: ['beaker', 'lab'], Component: LuBeaker },
      { id: 'Dna', keywords: ['dna', 'genetics'], Component: LuDna },
    ],
  },
  {
    id: 'actions',
    labelFr: 'Actions & interface',
    labelEn: 'Actions & interface',
    icons: [
      { id: 'Settings', keywords: ['settings', 'config'], Component: LuSettings },
      { id: 'Cog', keywords: ['cog', 'settings'], Component: LuCog },
      { id: 'Power', keywords: ['power', 'on'], Component: LuPower },
      { id: 'RefreshCw', keywords: ['refresh', 'reload'], Component: LuRefreshCw },
      { id: 'RotateCw', keywords: ['rotate'], Component: LuRotateCw },
      { id: 'Save', keywords: ['save'], Component: LuSave },
      { id: 'Download', keywords: ['download'], Component: LuDownload },
      { id: 'Upload', keywords: ['upload'], Component: LuUpload },
      { id: 'Share', keywords: ['share'], Component: LuShare },
      { id: 'Copy', keywords: ['copy'], Component: LuCopy },
      { id: 'Trash', keywords: ['trash', 'delete'], Component: LuTrash },
      { id: 'Trash2', keywords: ['trash', 'delete'], Component: LuTrash2 },
      { id: 'Plus', keywords: ['plus', 'add'], Component: LuPlus },
      { id: 'Minus', keywords: ['minus'], Component: LuMinus },
      { id: 'X', keywords: ['x', 'close'], Component: LuX },
      { id: 'ArrowRight', keywords: ['arrow', 'right'], Component: LuArrowRight },
      { id: 'ArrowLeft', keywords: ['arrow', 'left'], Component: LuArrowLeft },
      { id: 'ArrowUp', keywords: ['arrow', 'up'], Component: LuArrowUp },
      { id: 'ArrowDown', keywords: ['arrow', 'down'], Component: LuArrowDown },
      { id: 'ChevronRight', keywords: ['chevron', 'arrow'], Component: LuChevronRight },
      { id: 'MoreHorizontal', keywords: ['more', 'menu'], Component: LuMoreHorizontal },
    ],
  },
];

const allIcons = ICON_CATEGORIES.flatMap((c) => c.icons);
const iconsById = new Map(allIcons.map((i) => [i.id, i]));

export function getIconById(id: string): IconEntry | null {
  return iconsById.get(id) ?? null;
}

export function searchIcons(query: string): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  return allIcons.filter(
    (i) => i.id.toLowerCase().includes(q) || i.keywords.some((k) => k.includes(q))
  );
}

/**
 * Renders a lucide icon by id. Returns null when the id is unknown so
 * the caller can fall back to the raw string (e.g., an emoji or blank).
 */
export function LucideIcon({
  id,
  size = 22,
  color,
}: {
  id: string;
  size?: number;
  color?: string;
}): JSX.Element | null {
  const entry = getIconById(id);
  if (!entry) return null;
  const Cmp = entry.Component;
  return <Cmp size={size} color={color} strokeWidth={1.8} />;
}
