/**
 * FlashcardView — Filarr Notes
 *
 * Spaced repetition review flow.
 * Front -> reveal back -> rate difficulty (0-5).
 */

import React, { useState, useCallback, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import {
  loadDecks,
  saveDecks,
  getDueCards,
  reviewCard,
  parseFlashcards,
  createDeck,
  type FlashcardDeck,
  type Flashcard,
  type ReviewQuality,
} from '../../../services/notes/flashcardService';
import { useSelector } from 'react-redux';
import type { RootState } from '../../../store';
import './FlashcardView.css';

// ==================== Icons ====================

const CardIcon = () => (
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
    <rect x="2" y="4" width="20" height="16" rx="2" />
    <line x1="2" y1="10" x2="22" y2="10" />
  </svg>
);

// ==================== Difficulty Colors ====================

const QUALITY_LABELS: { q: ReviewQuality; label: string; color: string }[] = [
  { q: 0, label: 'Again', color: '#ef4444' },
  { q: 1, label: 'Hard', color: '#f97316' },
  { q: 3, label: 'Good', color: '#22c55e' },
  { q: 5, label: 'Easy', color: '#3b82f6' },
];

// ==================== Component ====================

interface FlashcardViewProps {
  onClose: () => void;
}

export const FlashcardView: React.FC<FlashcardViewProps> = React.memo(function FlashcardView({
  onClose,
}) {
  const { t } = useTranslation();
  const notesById = useSelector((s: RootState) => s.notes.byId);
  const [decks, setDecks] = useState<FlashcardDeck[]>([]);
  const [activeDeckIndex, setActiveDeckIndex] = useState(0);
  const [currentCardIndex, setCurrentCardIndex] = useState(0);
  const [isRevealed, setIsRevealed] = useState(false);
  const [showGenerator, setShowGenerator] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);

  // Load decks on mount
  useEffect(() => {
    setDecks(loadDecks());
  }, []);

  const activeDeck = decks[activeDeckIndex] || null;
  const dueCards = useMemo(() => (activeDeck ? getDueCards(activeDeck) : []), [activeDeck]);
  const currentCard = dueCards[currentCardIndex] || null;

  const handleRate = useCallback(
    (quality: ReviewQuality) => {
      if (!currentCard || !activeDeck) return;

      const updated = reviewCard(currentCard, quality);
      const newCards = activeDeck.cards.map((c) => (c.id === updated.id ? updated : c));
      const newDeck = { ...activeDeck, cards: newCards, updatedAt: new Date().toISOString() };
      const newDecks = decks.map((d, i) => (i === activeDeckIndex ? newDeck : d));
      setDecks(newDecks);
      saveDecks(newDecks);

      // Advance
      setIsRevealed(false);
      if (currentCardIndex < dueCards.length - 1) {
        setCurrentCardIndex((i) => i + 1);
      } else {
        setCurrentCardIndex(0);
      }
    },
    [currentCard, activeDeck, activeDeckIndex, decks, currentCardIndex, dueCards.length]
  );

  // Keyboard review: Space/Enter reveals the answer, then 1-4 rate the card.
  // Spaced-repetition is repeated dozens of times per session, so pointer-only
  // review is a real friction + accessibility gap.
  useEffect(() => {
    if (showGenerator || !currentCard) return;
    const onKey = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName;
      if (tag === 'INPUT' || tag === 'TEXTAREA') return;
      if (!isRevealed) {
        if (e.key === ' ' || e.key === 'Enter') {
          e.preventDefault();
          setIsRevealed(true);
        }
        return;
      }
      const idx = ['1', '2', '3', '4'].indexOf(e.key);
      if (idx !== -1) {
        e.preventDefault();
        handleRate(QUALITY_LABELS[idx].q);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [showGenerator, currentCard, isRevealed, handleRate]);

  const handleGenerateFromNotes = useCallback(() => {
    setGenerateError(null);
    const parsedCards: Flashcard[] = [];
    for (const note of Object.values(notesById)) {
      if (note.deletedAt || !note.plainText) continue;
      parsedCards.push(...parseFlashcards(note.plainText, note.id));
    }

    if (parsedCards.length === 0) {
      setGenerateError(
        t(
          'notes.noFlashcardsFound',
          'No Q:/A: pairs found in your notes. Add "Q: question" and "A: answer" on consecutive lines.'
        )
      );
      return;
    }

    // Reconcile against the single reused 'Auto-generated' deck instead of
    // minting a fresh one: surviving cards keep their SM-2 review progress
    // (ease/interval/reps/schedule), new pairs are added, removed pairs drop.
    const autoName = t('notes.autoGeneratedDeck', 'Auto-generated');
    const keyOf = (c: Flashcard) => `${c.noteId}::${c.question.trim().toLowerCase()}`;
    const existingIdx = decks.findIndex((d) => d.name === autoName);
    const prevByKey = new Map<string, Flashcard>(
      existingIdx >= 0 ? decks[existingIdx].cards.map((c) => [keyOf(c), c]) : []
    );

    const reconciled: Flashcard[] = parsedCards.map((pc) => {
      const prev = prevByKey.get(keyOf(pc));
      // Keep the prior card's identity + SM-2 progress; refresh the answer text.
      return prev ? { ...prev, answer: pc.answer, noteId: pc.noteId } : pc;
    });

    let newDecks: typeof decks;
    let targetIdx: number;
    if (existingIdx >= 0) {
      newDecks = decks.map((d, i) => (i === existingIdx ? { ...d, cards: reconciled } : d));
      targetIdx = existingIdx;
    } else {
      const deck = createDeck(autoName);
      deck.cards = reconciled;
      newDecks = [...decks, deck];
      targetIdx = newDecks.length - 1;
    }

    setDecks(newDecks);
    saveDecks(newDecks);
    setActiveDeckIndex(targetIdx);
    setCurrentCardIndex(0);
    setShowGenerator(false);
  }, [notesById, decks, t]);

  return (
    <div className="flashcard-view__overlay" onClick={onClose}>
      <div className="flashcard-view" onClick={(e) => e.stopPropagation()}>
        <div className="flashcard-view__header">
          <CardIcon />
          <h3>{t('notes.flashcards', 'Flashcards')}</h3>
          <span className="flashcard-view__count">
            {dueCards.length} {t('notes.cardsRemaining', 'due')}
          </span>
          <button className="flashcard-view__close" onClick={onClose}>
            &times;
          </button>
        </div>

        {decks.length === 0 ? (
          <div className="flashcard-view__empty">
            <p>{t('notes.noDecks', 'No flashcard decks yet')}</p>
            <p className="flashcard-view__hint">
              {t('notes.flashcardHint', 'Add Q:/A: pairs in your notes, then generate flashcards.')}
            </p>
            <button className="flashcard-view__generate-btn" onClick={handleGenerateFromNotes}>
              {t('notes.generateFromNotes', 'Generate from Notes')}
            </button>
            {generateError && (
              <p
                className="flashcard-view__hint"
                style={{ color: 'var(--color-warning-600, #d97706)', marginTop: 8 }}
              >
                {generateError}
              </p>
            )}
          </div>
        ) : !currentCard ? (
          <div className="flashcard-view__empty">
            <p>{t('notes.allReviewed', 'All cards reviewed! Come back later.')}</p>
          </div>
        ) : (
          <div className="flashcard-view__card-area">
            <div
              className={`flashcard-card ${isRevealed ? 'flashcard-card--revealed' : ''}`}
              role="button"
              tabIndex={0}
              aria-expanded={isRevealed}
              aria-label={
                isRevealed ? t('notes.answer', 'Answer') : t('notes.tapToReveal', 'Click to reveal')
              }
              onClick={() => !isRevealed && setIsRevealed(true)}
              onKeyDown={(e) => {
                if (!isRevealed && (e.key === 'Enter' || e.key === ' ')) {
                  e.preventDefault();
                  setIsRevealed(true);
                }
              }}
            >
              <div className="flashcard-card__front">
                <span className="flashcard-card__label">{t('notes.question', 'Question')}</span>
                <p className="flashcard-card__text">{currentCard.question}</p>
              </div>
              {isRevealed && (
                <div className="flashcard-card__back" aria-live="polite">
                  <span className="flashcard-card__label">{t('notes.answer', 'Answer')}</span>
                  <p className="flashcard-card__text">{currentCard.answer}</p>
                </div>
              )}
              {!isRevealed && (
                <p className="flashcard-card__tap">
                  {t('notes.tapToReveal', 'Click to reveal')} · <kbd>Space</kbd>
                </p>
              )}
            </div>

            {isRevealed && (
              <div className="flashcard-view__rating">
                {QUALITY_LABELS.map(({ q, label, color }, i) => (
                  <button
                    key={q}
                    className="flashcard-view__rate-btn"
                    style={{ borderColor: color, color }}
                    onClick={() => handleRate(q)}
                    aria-keyshortcuts={String(i + 1)}
                    title={`${label} (${i + 1})`}
                  >
                    <span className="flashcard-view__rate-key">{i + 1}</span> {label}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}

        {decks.length > 0 && (
          <div className="flashcard-view__footer">
            <select
              className="flashcard-view__deck-select"
              value={activeDeckIndex}
              onChange={(e) => {
                setActiveDeckIndex(Number(e.target.value));
                setCurrentCardIndex(0);
                setIsRevealed(false);
              }}
            >
              {decks.map((d, i) => (
                <option key={d.id} value={i}>
                  {d.name} ({d.cards.length})
                </option>
              ))}
            </select>
            <button
              className="flashcard-view__generate-btn flashcard-view__generate-btn--small"
              onClick={handleGenerateFromNotes}
            >
              + {t('notes.generateFromNotes', 'Generate')}
            </button>
          </div>
        )}
      </div>
    </div>
  );
});

export default FlashcardView;
